package ui

const (
	// Icons
	ICON_DONE   = ''
	ICON_FAILED = ''
	ICON_DOT    = ''

	// Status Types
	STATUS_LOGIN = iota
	STATUS_CREATE
	STATUS_CHATS_LOAD
	STATUS_CHAT_LOAD
	STATUS_REQUEST_LOAD
	STATUS_REQUEST_RECV
	STATUS_DIRECT_REQUEST_SEND
	STATUS_GROUP_REQUEST_SEND
	STATUS_GROUP_CREATE_SEND
	STATUS_REQUEST_ACTION_SEND
	STATUS_MESSAGE_RECV
	STATUS_MESSAGE_SEND
)
